name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/istockphoto-1265118956-612x612-2.png
    - assets/page-1/images/ellipse-5.png
    - assets/page-1/images/f193731868afoycvhhgisrkb6iao0kkqrvixu47nvy-1.png
    - assets/page-2/images/auto-group-saxo.png
    - assets/page-2/images/auto-group-8bmf.png
    - assets/page-1/images/arrow-back.png
    - assets/page-1/images/ellipse-4.png
    - assets/page-1/images/icon-google.png
    - assets/page-1/images/chevron-right.png
    - assets/page-1/images/hide.png
    - assets/page-1/images/icon-menu.png
    - assets/page-1/images/icon-menu-BmX.png
    - assets/page-1/images/images-1-bg.png
    - assets/page-2/images/auto-group-el7x.png
    - assets/page-2/images/auto-group-9ozm.png
    - assets/page-1/images/ellipse-2.png
    - assets/page-2/images/auto-group-63ps.png
    - assets/page-2/images/istockphoto-1265118956-612x612-2-NoF.png
    - assets/page-1/images/ellipse-1.png
    - assets/page-2/images/auto-group-wtay.png
    - assets/page-1/images/ellipse-3.png
    - assets/page-1/images/ellipse-3-jvV.png
    - assets/page-1/images/auto-group-arcr.png
    - assets/page-1/images/auto-group-vxmw.png
    - assets/page-1/images/download-1.png
    - assets/page-2/images/auto-group-e93b.png
    - assets/page-1/images/hide-ctD.png
    - assets/page-1/images/arrow-back-jxq.png
    - assets/page-1/images/icon-pause.png
    - assets/page-2/images/auto-group-m3vm.png
    - assets/page-1/images/auto-group-6nxf.png
    - assets/page-2/images/images-1-bg-4mb.png
    - assets/page-1/images/auto-group-mlow.png
    - assets/page-1/images/ellipse-1-9BK.png
    - assets/page-1/images/icon-video.png
    - assets/page-1/images/icon-question.png
    - assets/page-1/images/icon-speaker.png
    - assets/page-1/images/auto-group-pm9o.png
    - assets/page-1/images/icon-menu-e8V.png
    - assets/page-2/images/flat-design-trophy-trophy-isolated-on-white-background-free-vector-1.png
    - assets/page-1/images/ellipse-2-wSM.png
    - assets/page-1/images/f3235079570gqgkuqu7zstf7sgj0jssjy7tnm0bgg2-1.png
    - assets/page-1/images/imageprocessing20220208-32547-eq0h71-1-bg.png
    - assets/page-2/images/auto-group-us6d.png
    - assets/page-1/images/hide-6Gu.png
    - assets/page-1/images/push-up-gif-1.png
    - assets/page-1/images/auto-group-fgxv.png
    - assets/page-1/images/flat-design-trophy-trophy-isolated-on-white-background-free-vector-1-vPo.png
    - assets/page-1/images/back.png
    - assets/page-2/images/chevron-right-kTX.png
    - assets/page-2/images/auto-group-qslr.png
    - assets/page-2/images/auto-group-akjf.png
    - assets/page-1/images/logo-1.png
    - assets/page-1/images/icon-menu-ths.png
    - assets/page-2/images/auto-group-nrc9.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/auto-group-wj3w.png
    - assets/page-1/images/juan-morel-preacher-curl-arms-1.png
    - assets/page-1/images/guy-showing-off-abs-and-chest-1.png
    - assets/page-1/images/bodybuilder-dumbbells-gym-1280-1.png
    - assets/page-1/images/background.png
    - assets/page-2/images/background-8bP.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
